// Code generated by go-swagger; DO NOT EDIT.

package query

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/bureau14/qdb-api-rest/models"
)

// PostQueryOKCode is the HTTP code returned for type PostQueryOK
const PostQueryOKCode int = 200

/*PostQueryOK Successful operation

swagger:response postQueryOK
*/
type PostQueryOK struct {

	/*
	  In: Body
	*/
	Payload *models.QueryResult `json:"body,omitempty"`
}

// NewPostQueryOK creates PostQueryOK with default headers values
func NewPostQueryOK() *PostQueryOK {

	return &PostQueryOK{}
}

// WithPayload adds the payload to the post query o k response
func (o *PostQueryOK) WithPayload(payload *models.QueryResult) *PostQueryOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post query o k response
func (o *PostQueryOK) SetPayload(payload *models.QueryResult) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostQueryOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostQueryBadRequestCode is the HTTP code returned for type PostQueryBadRequest
const PostQueryBadRequestCode int = 400

/*PostQueryBadRequest Bad Request.

swagger:response postQueryBadRequest
*/
type PostQueryBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.QdbError `json:"body,omitempty"`
}

// NewPostQueryBadRequest creates PostQueryBadRequest with default headers values
func NewPostQueryBadRequest() *PostQueryBadRequest {

	return &PostQueryBadRequest{}
}

// WithPayload adds the payload to the post query bad request response
func (o *PostQueryBadRequest) WithPayload(payload *models.QdbError) *PostQueryBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post query bad request response
func (o *PostQueryBadRequest) SetPayload(payload *models.QdbError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostQueryBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostQueryInternalServerErrorCode is the HTTP code returned for type PostQueryInternalServerError
const PostQueryInternalServerErrorCode int = 500

/*PostQueryInternalServerError Internal Error.

swagger:response postQueryInternalServerError
*/
type PostQueryInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.QdbError `json:"body,omitempty"`
}

// NewPostQueryInternalServerError creates PostQueryInternalServerError with default headers values
func NewPostQueryInternalServerError() *PostQueryInternalServerError {

	return &PostQueryInternalServerError{}
}

// WithPayload adds the payload to the post query internal server error response
func (o *PostQueryInternalServerError) WithPayload(payload *models.QdbError) *PostQueryInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post query internal server error response
func (o *PostQueryInternalServerError) SetPayload(payload *models.QdbError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostQueryInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
