// Code generated by go-swagger; DO NOT EDIT.

package option

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/bureau14/qdb-api-rest/models"
)

// GetParallelismHandlerFunc turns a function with the right signature into a get parallelism handler
type GetParallelismHandlerFunc func(GetParallelismParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn GetParallelismHandlerFunc) Handle(params GetParallelismParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// GetParallelismHandler interface for that can handle valid get parallelism params
type GetParallelismHandler interface {
	Handle(GetParallelismParams, *models.Principal) middleware.Responder
}

// NewGetParallelism creates a new http.Handler for the get parallelism operation
func NewGetParallelism(ctx *middleware.Context, handler GetParallelismHandler) *GetParallelism {
	return &GetParallelism{Context: ctx, Handler: handler}
}

/* GetParallelism swagger:route GET /option/parallelism option parallelism getParallelism

Get the client max parallelism for this logged-in user

*/
type GetParallelism struct {
	Context *middleware.Context
	Handler GetParallelismHandler
}

func (o *GetParallelism) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetParallelismParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
