// Code generated by go-swagger; DO NOT EDIT.

package option

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/bureau14/qdb-api-rest/models"
)

// GetMaxInBufferSizeOKCode is the HTTP code returned for type GetMaxInBufferSizeOK
const GetMaxInBufferSizeOKCode int = 200

/*GetMaxInBufferSizeOK Successful operation

swagger:response getMaxInBufferSizeOK
*/
type GetMaxInBufferSizeOK struct {

	/*
	  In: Body
	*/
	Payload int64 `json:"body,omitempty"`
}

// NewGetMaxInBufferSizeOK creates GetMaxInBufferSizeOK with default headers values
func NewGetMaxInBufferSizeOK() *GetMaxInBufferSizeOK {

	return &GetMaxInBufferSizeOK{}
}

// WithPayload adds the payload to the get max in buffer size o k response
func (o *GetMaxInBufferSizeOK) WithPayload(payload int64) *GetMaxInBufferSizeOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get max in buffer size o k response
func (o *GetMaxInBufferSizeOK) SetPayload(payload int64) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetMaxInBufferSizeOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetMaxInBufferSizeBadRequestCode is the HTTP code returned for type GetMaxInBufferSizeBadRequest
const GetMaxInBufferSizeBadRequestCode int = 400

/*GetMaxInBufferSizeBadRequest Bad Request.

swagger:response getMaxInBufferSizeBadRequest
*/
type GetMaxInBufferSizeBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.QdbError `json:"body,omitempty"`
}

// NewGetMaxInBufferSizeBadRequest creates GetMaxInBufferSizeBadRequest with default headers values
func NewGetMaxInBufferSizeBadRequest() *GetMaxInBufferSizeBadRequest {

	return &GetMaxInBufferSizeBadRequest{}
}

// WithPayload adds the payload to the get max in buffer size bad request response
func (o *GetMaxInBufferSizeBadRequest) WithPayload(payload *models.QdbError) *GetMaxInBufferSizeBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get max in buffer size bad request response
func (o *GetMaxInBufferSizeBadRequest) SetPayload(payload *models.QdbError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetMaxInBufferSizeBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
