// Code generated by go-swagger; DO NOT EDIT.

package option

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/bureau14/qdb-api-rest/models"
)

// MaxInBufferSizeHandlerFunc turns a function with the right signature into a max in buffer size handler
type MaxInBufferSizeHandlerFunc func(MaxInBufferSizeParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn MaxInBufferSizeHandlerFunc) Handle(params MaxInBufferSizeParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// MaxInBufferSizeHandler interface for that can handle valid max in buffer size params
type MaxInBufferSizeHandler interface {
	Handle(MaxInBufferSizeParams, *models.Principal) middleware.Responder
}

// NewMaxInBufferSize creates a new http.Handler for the max in buffer size operation
func NewMaxInBufferSize(ctx *middleware.Context, handler MaxInBufferSizeHandler) *MaxInBufferSize {
	return &MaxInBufferSize{Context: ctx, Handler: handler}
}

/* MaxInBufferSize swagger:route GET /option/get-max-in-buffer-size option max-in-buffer-size maxInBufferSize

Get the client max in buffer size

*/
type MaxInBufferSize struct {
	Context *middleware.Context
	Handler MaxInBufferSizeHandler
}

func (o *MaxInBufferSize) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewMaxInBufferSizeParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
