// Code generated by go-swagger; DO NOT EDIT.

package option

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/bureau14/qdb-api-rest/models"
)

// MaxInBufferSizeOKCode is the HTTP code returned for type MaxInBufferSizeOK
const MaxInBufferSizeOKCode int = 200

/*MaxInBufferSizeOK Successful operation

swagger:response maxInBufferSizeOK
*/
type MaxInBufferSizeOK struct {

	/*
	  In: Body
	*/
	Payload int64 `json:"body,omitempty"`
}

// NewMaxInBufferSizeOK creates MaxInBufferSizeOK with default headers values
func NewMaxInBufferSizeOK() *MaxInBufferSizeOK {

	return &MaxInBufferSizeOK{}
}

// WithPayload adds the payload to the max in buffer size o k response
func (o *MaxInBufferSizeOK) WithPayload(payload int64) *MaxInBufferSizeOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the max in buffer size o k response
func (o *MaxInBufferSizeOK) SetPayload(payload int64) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *MaxInBufferSizeOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// MaxInBufferSizeBadRequestCode is the HTTP code returned for type MaxInBufferSizeBadRequest
const MaxInBufferSizeBadRequestCode int = 400

/*MaxInBufferSizeBadRequest Bad Request.

swagger:response maxInBufferSizeBadRequest
*/
type MaxInBufferSizeBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.QdbError `json:"body,omitempty"`
}

// NewMaxInBufferSizeBadRequest creates MaxInBufferSizeBadRequest with default headers values
func NewMaxInBufferSizeBadRequest() *MaxInBufferSizeBadRequest {

	return &MaxInBufferSizeBadRequest{}
}

// WithPayload adds the payload to the max in buffer size bad request response
func (o *MaxInBufferSizeBadRequest) WithPayload(payload *models.QdbError) *MaxInBufferSizeBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the max in buffer size bad request response
func (o *MaxInBufferSizeBadRequest) SetPayload(payload *models.QdbError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *MaxInBufferSizeBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
