// Code generated by go-swagger; DO NOT EDIT.

package option

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/bureau14/qdb-api-rest/models"
)

// SetParallelismHandlerFunc turns a function with the right signature into a set parallelism handler
type SetParallelismHandlerFunc func(SetParallelismParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn SetParallelismHandlerFunc) Handle(params SetParallelismParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// SetParallelismHandler interface for that can handle valid set parallelism params
type SetParallelismHandler interface {
	Handle(SetParallelismParams, *models.Principal) middleware.Responder
}

// NewSetParallelism creates a new http.Handler for the set parallelism operation
func NewSetParallelism(ctx *middleware.Context, handler SetParallelismHandler) *SetParallelism {
	return &SetParallelism{Context: ctx, Handler: handler}
}

/* SetParallelism swagger:route POST /option/parallelism option parallelism setParallelism

Set the client max parallelism for this logged-in user

*/
type SetParallelism struct {
	Context *middleware.Context
	Handler SetParallelismHandler
}

func (o *SetParallelism) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewSetParallelismParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
