// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetTableCsvOKCode is the HTTP code returned for type GetTableCsvOK
const GetTableCsvOKCode int = 200

/*GetTableCsvOK Successful operation

swagger:response getTableCsvOK
*/
type GetTableCsvOK struct {

	/*
	  In: Body
	*/
	Payload io.ReadCloser `json:"body,omitempty"`
}

// NewGetTableCsvOK creates GetTableCsvOK with default headers values
func NewGetTableCsvOK() *GetTableCsvOK {

	return &GetTableCsvOK{}
}

// WithPayload adds the payload to the get table csv o k response
func (o *GetTableCsvOK) WithPayload(payload io.ReadCloser) *GetTableCsvOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get table csv o k response
func (o *GetTableCsvOK) SetPayload(payload io.ReadCloser) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTableCsvOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetTableCsvBadRequestCode is the HTTP code returned for type GetTableCsvBadRequest
const GetTableCsvBadRequestCode int = 400

/*GetTableCsvBadRequest Bad Request.

swagger:response getTableCsvBadRequest
*/
type GetTableCsvBadRequest struct {
}

// NewGetTableCsvBadRequest creates GetTableCsvBadRequest with default headers values
func NewGetTableCsvBadRequest() *GetTableCsvBadRequest {

	return &GetTableCsvBadRequest{}
}

// WriteResponse to the client
func (o *GetTableCsvBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// GetTableCsvInternalServerErrorCode is the HTTP code returned for type GetTableCsvInternalServerError
const GetTableCsvInternalServerErrorCode int = 500

/*GetTableCsvInternalServerError Internal Error.

swagger:response getTableCsvInternalServerError
*/
type GetTableCsvInternalServerError struct {
}

// NewGetTableCsvInternalServerError creates GetTableCsvInternalServerError with default headers values
func NewGetTableCsvInternalServerError() *GetTableCsvInternalServerError {

	return &GetTableCsvInternalServerError{}
}

// WriteResponse to the client
func (o *GetTableCsvInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
