// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/bureau14/qdb-api-rest/models"
)

// GetTableCsvHandlerFunc turns a function with the right signature into a get table csv handler
type GetTableCsvHandlerFunc func(GetTableCsvParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn GetTableCsvHandlerFunc) Handle(params GetTableCsvParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// GetTableCsvHandler interface for that can handle valid get table csv params
type GetTableCsvHandler interface {
	Handle(GetTableCsvParams, *models.Principal) middleware.Responder
}

// NewGetTableCsv creates a new http.Handler for the get table csv operation
func NewGetTableCsv(ctx *middleware.Context, handler GetTableCsvHandler) *GetTableCsv {
	return &GetTableCsv{Context: ctx, Handler: handler}
}

/*GetTableCsv swagger:route GET /tables/{name}.csv getTableCsv

Fetch the rows of a table between a given date range and return as csv

*/
type GetTableCsv struct {
	Context *middleware.Context
	Handler GetTableCsvHandler
}

func (o *GetTableCsv) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetTableCsvParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
