// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/bureau14/qdb-api-rest/models"
)

// PrometheusWriteOKCode is the HTTP code returned for type PrometheusWriteOK
const PrometheusWriteOKCode int = 200

/*PrometheusWriteOK OK

swagger:response prometheusWriteOK
*/
type PrometheusWriteOK struct {
}

// NewPrometheusWriteOK creates PrometheusWriteOK with default headers values
func NewPrometheusWriteOK() *PrometheusWriteOK {

	return &PrometheusWriteOK{}
}

// WriteResponse to the client
func (o *PrometheusWriteOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// PrometheusWriteInternalServerErrorCode is the HTTP code returned for type PrometheusWriteInternalServerError
const PrometheusWriteInternalServerErrorCode int = 500

/*PrometheusWriteInternalServerError Internal Error.

swagger:response prometheusWriteInternalServerError
*/
type PrometheusWriteInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.QdbError `json:"body,omitempty"`
}

// NewPrometheusWriteInternalServerError creates PrometheusWriteInternalServerError with default headers values
func NewPrometheusWriteInternalServerError() *PrometheusWriteInternalServerError {

	return &PrometheusWriteInternalServerError{}
}

// WithPayload adds the payload to the prometheus write internal server error response
func (o *PrometheusWriteInternalServerError) WithPayload(payload *models.QdbError) *PrometheusWriteInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the prometheus write internal server error response
func (o *PrometheusWriteInternalServerError) SetPayload(payload *models.QdbError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PrometheusWriteInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
