// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/bureau14/qdb-api-rest/models"
)

// StatusOKCode is the HTTP code returned for type StatusOK
const StatusOKCode int = 200

/*StatusOK Successful operation

swagger:response statusOK
*/
type StatusOK struct {
}

// NewStatusOK creates StatusOK with default headers values
func NewStatusOK() *StatusOK {

	return &StatusOK{}
}

// WriteResponse to the client
func (o *StatusOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// StatusBadRequestCode is the HTTP code returned for type StatusBadRequest
const StatusBadRequestCode int = 400

/*StatusBadRequest Bad Request.

swagger:response statusBadRequest
*/
type StatusBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.QdbError `json:"body,omitempty"`
}

// NewStatusBadRequest creates StatusBadRequest with default headers values
func NewStatusBadRequest() *StatusBadRequest {

	return &StatusBadRequest{}
}

// WithPayload adds the payload to the status bad request response
func (o *StatusBadRequest) WithPayload(payload *models.QdbError) *StatusBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the status bad request response
func (o *StatusBadRequest) SetPayload(payload *models.QdbError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *StatusBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
