// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// StatusReadinessHandlerFunc turns a function with the right signature into a status readiness handler
type StatusReadinessHandlerFunc func(StatusReadinessParams) middleware.Responder

// Handle executing the request and returning a response
func (fn StatusReadinessHandlerFunc) Handle(params StatusReadinessParams) middleware.Responder {
	return fn(params)
}

// StatusReadinessHandler interface for that can handle valid status readiness params
type StatusReadinessHandler interface {
	Handle(StatusReadinessParams) middleware.Responder
}

// NewStatusReadiness creates a new http.Handler for the status readiness operation
func NewStatusReadiness(ctx *middleware.Context, handler StatusReadinessHandler) *StatusReadiness {
	return &StatusReadiness{Context: ctx, Handler: handler}
}

/* StatusReadiness swagger:route GET /status/readiness statusReadiness

StatusReadiness status readiness API

*/
type StatusReadiness struct {
	Context *middleware.Context
	Handler StatusReadinessHandler
}

func (o *StatusReadiness) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewStatusReadinessParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
