// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi QuasarDB API
Find out more at https://doc.quasardb.net


    Schemes:
      http
      https
    Host: localhost
    BasePath: /api
    Version: 3.6.0-nightly.0

    Consumes:
    - application/json
    - application/x-protobuf

    Produces:
    - application/json
    - application/x-protobuf
    - text/csv

swagger:meta
*/
package restapi
