// Code generated by go-swagger; DO NOT EDIT.

// Package restapi QuasarDB API
//
//  Find out more at https://doc.quasardb.net
//  Schemes:
//    http
//    https
//  Host: localhost
//  BasePath: /api
//  Version: 3.8.6
//
//  Consumes:
//    - application/json
//    - application/x-protobuf
//
//  Produces:
//    - text/csv
//    - application/json
//    - application/x-protobuf
//
// swagger:meta
package restapi
