// Code generated by go-swagger; DO NOT EDIT.

package cluster

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	models "github.com/bureau14/qdb-api-rest/models"
)

// GetNodeHandlerFunc turns a function with the right signature into a get node handler
type GetNodeHandlerFunc func(GetNodeParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn GetNodeHandlerFunc) Handle(params GetNodeParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// GetNodeHandler interface for that can handle valid get node params
type GetNodeHandler interface {
	Handle(GetNodeParams, *models.Principal) middleware.Responder
}

// NewGetNode creates a new http.Handler for the get node operation
func NewGetNode(ctx *middleware.Context, handler GetNodeHandler) *GetNode {
	return &GetNode{Context: ctx, Handler: handler}
}

/*GetNode swagger:route GET /cluster/nodes/{id} cluster getNode

Get information about a single node in the cluster

*/
type GetNode struct {
	Context *middleware.Context
	Handler GetNodeHandler
}

func (o *GetNode) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetNodeParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
